language: objective-c
osx_image: xcode8.3
before_install:
 - External/objective-git/script/bootstrap
script:
 - set -o pipefail && xcodebuild -workspace GitX.xcworkspace -scheme GitX build | xcpretty
